# These are supported funding model platforms
# This file adds the "Sponsor" button to the GitHub repo

github: [gsepcore]
# ko_fi: # Replace with your Ko-fi username if desired
# open_collective: # Replace with your Open Collective username if desired
# custom: ["https://gsepcore.com/sponsor"]
